version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - engine
      - mongo

  engine:
    build: .audio-processing
    ports:
      - '5000:5000'

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'

volumes:
  mongo_data:
